### ISSUE TITLE
Question about the  k-Prototype 

### ISSUE THREAD

**Issue by Anisou20** [nicodv/kmodes#10]
Dear Nico
Thank you very much for this python code !
In fact, i have a question about the algorithm k-Prototype implemented in this work.
I wanted to know if it is possible to assign some weighted coefficients to each families of variables ( like various probabilities : 0.7 for numeric data and 0.3 for categories) in the order to give more importance to some classification than other.
Thank You for any response.

**Comment by nicodv** [comment]
The `gamma` coefficient does exactly this. Check it out: https://github.com/nicodv/kmodes/blob/master/kmodes/kprototypes.py#L284
