### ISSUE TITLE
Parallel Computing

### ISSUE THREAD

**Issue by shmulik90** [nicodv/kmodes#100]
Hi!
I somehow don't manage an implementation of the parrallel Computation... 
I get an error as follows:
![grafik](https://user-images.githubusercontent.com/38791059/51269250-fd2b4580-198f-11e9-8fac-fd04edc19faf.png)

Furthermore I'm pretty new to this topic but I wondered what the difference would be if i just reduce my data to the Objects (X1,X2,...,Xn) which are unique - how would that affect the outcome? 
As far as I can see from the theorem in the paper:
![grafik](https://user-images.githubusercontent.com/38791059/51269478-9e1a0080-1990-11e9-9cdb-6e4d08c08d5e.png)
it basically tells us that the frequency of an attribute's category should be bigger within a cluster than in the whole set of objects- right?
And if that is so, then if i only take the unique objects how would that change my result?

**Comment by nicodv** [comment]
You're probably using 0.9, @shmulik90 . That feature is only available when you build the latest version from source.

Re your second question: you would be underweighting the areas where there are a lot of duplicates. Depending on your data/application this may or may not be a wise thing to do.

**Comment by shmulik90** [comment]
Sry- the latest version i can see is 0.9- isn't it?

**Comment by sharma-ji** [comment]
Hi! I am facing same issue with `n_jobs`.
And the latest version is 0.9
![capture](https://user-images.githubusercontent.com/17575809/51734108-748d6300-207b-11e9-9ab2-d237297054db.PNG)

**Comment by nicodv** [comment]
Guys, 0.9 is the latest release. What you see on the master branch in Github is newer than that. You can build it from source if you'd like.
