### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by klepikhina** [nicodv/kmodes#105]
Hi - When running K-Prototypes on a matrix of shape ~4000x20 or one with more rows (with ~50% being categorical), I encounter a memory error `OSError: [Errno 12] Cannot allocate memory
`. When working with large matrices, is this most likely a local error or does K-Prototypes have difficulty scaling?

**Comment by nicodv** [comment]
That's a very small matrix, actually. :) This is likely not related to `kmodes`
