### ISSUE TITLE
cluster_centroids_ fails when KModes given explicit initialization

### ISSUE THREAD

**Issue by ecotner** [nicodv/kmodes#106]
I'm trying to extract the cluster centroids after calling km.fit on my data. The actual fitting procedure completes without any problems, but when I try to get the centroids I get the following error:

```
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 3311, cost: 277548.0
Run 1, iteration: 2/100, moves: 3157, cost: 273702.0
Run 1, iteration: 3/100, moves: 3085, cost: 274505.0
Done fitting
Traceback (most recent call last):
  File "clustering_generate_excel.py", line 145, in <module>
    centroid_init = kp.cluster_centroids_
  File "/home/ecotner/anaconda3/lib/python3.7/site-packages/kmodes/kmodes.py", line 405, in cluster_centroids_
    return decode_centroids(self._enc_cluster_centroids, self._enc_map)
  File "/home/ecotner/anaconda3/lib/python3.7/site-packages/kmodes/util/__init__.py", line 64, in decode_centroids
    decoded.append(np.vectorize(inv_mapping.__getitem__)(encoded[:, ii]))
  File "/home/ecotner/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/ecotner/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2048, in _vectorize_call
    outputs = ufunc(*inputs)
KeyError: 255
```
The weird thing though is that this error only occurs if I pass an ndarray into KModes with the `init` keyword. The docs say that this is supported, but apparently it's not. The error appears regardless of the numbers in the array, even if they're the centroids that I just got from fitting (I tried random initialization too)! If I just use `init='Huang'` or `init='Cao'`, everything executes cleanly and I can extract the centroids just fine. When I check the underlying km._enc_cluster_centroids attribute, this is well-defined and returns an ndarray, but I don't know how to interpret these numbers. It seems like the error lies in however the _enc_cluster_centroid is decoded (in the decode_centroids function), but I don't understand what's happening there as the helper functions are split up over multiple files.

The code snippet that is generating this error is
```python
if LOAD_PREVIOUS_CENTROIDS:
    with open('./centroids.pickle', mode='rb') as fo:
        centroid_init = pickle.load(fo)
        #centroid_init = np.random.randint(15, size=(15,8))
else:
    centroid_init = 'Huang'
kp = KModes(n_clusters=NUM_CLUSTERS,
            init=centroid_init,
            n_init=1,
            verbose=1)
c = kp.fit_predict(id_df.values)
print('Done fitting')
centroid_init = kp.cluster_centroids_
with open('./centroids.pickle', mode='wb') as fo:
    pickle.dump(centroid_init, fo)
```
So you can see that if I were to run this, the centroids from the fit would essentially get plugged back in as initialization, and this still fails.

Any ideas? I'm running python 3.7, with kmodes version 0.9, scikit-learn version 0.19.2, numpy version 1.15.4., scipy version 1.1.0

**Comment by nicodv** [comment]
@ecotner , the `255` gives me a clue. In kmodes 0.9, the maximum number of clusters is 256, since we use `numpy` `uint8`s. I've changed it to `uint16`s later on. Do you set `k` > 256?

Also, are you sure `centroid_init` is the right shape and size? Check out the tests for examples of how to use the manual initialization: https://github.com/nicodv/kmodes/blob/master/kmodes/tests/test_kmodes.py#L142

**Comment by ecotner** [comment]
@nicodv no, I'm only trying it with `k=15` at the moment. I'm also very sure that the init is the right shape/size( `centroid_init.shape` returns `(15, 8)` and I'm using 8 features with 15 clusters) - I'm using the output from a previous `kp.cluster_centroids_` as the initialization:
```
>>> centroid_init
array([[ 14,   0,  16,   0,  -1,  -1, 158, 115],
       [  2,   0,   3,   3, 127, 105, 295, 197],
       [ 10,   2,  12,   3, 136,  20,  77,  42],
       [  2,   0,   3,   4, 127,  55, 150,  63],
       [  1,   0,  21,   5,  39,  -1, 124,  90],
       [ 17,   2,  12,   3,  22, 175, 242, 164],
       [  5,   1,   7,  -1,  -1,  -1,  69,  38],
       [  3,   3,   6,  -1,  -1,  -1, 267, 175],
       [  1,   0,  21,   4,  71,  -1, 276, 196],
       [ 11,   2,  12,   5,  -1,  -1, 209, 148],
       [  2,   0,   3,   5, 127, 105, 375, 263],
       [  2,   0,   3,   4,  28, 105,  16,   8],
       [ 13,   2,  12,  -1,  -1,  -1, 263, 187],
       [  6,   2,   6,   4,  21,  20, 370, 256],
       [ 10,   2,  12,   3, 136, 137,  59,  31]])
```
There are a lot of categories in the last couple features, which is why those numbers are so high. That shouldn't be a problem though, right? There are also a lot of -1's in there (which I believe correspond to NaN), I tried clipping those to zero, but it didn't help.

**Comment by ecotner** [comment]
I think I may have found another clue: calling `kp._enc_cluster_centroids` attribute has no problem at all, only the categories are clipped to be between 0 and 255 (inclusive). However even clipping the input centroids still throws the same error when calling `kp.cluster_centroids_`. I think the error may lie in the `KModes.decode_centroids` function.

**Comment by nicodv** [comment]
@ecotner , I found the issue. It's because of this line: https://github.com/nicodv/kmodes/blob/0.9/kmodes/util/__init__.py#L34

Since we already have integer data, we try be smart and skip the encoding to integers. However, because there are negative values in the data, the _unsigned_ integer type converts these to 255 (or in later versions of `kmodes` to 65535).

The solution is to not skip integer encoding, since negative values are reasonable in the input data. I'll put this in the next release.

For now, you can solve this by avoiding negative integers in your input data and initial centroids. Try encoding them as `9999` or a string. BTW, clipping both the data and the initial centroids to 0 also solved it for me.

**Comment by nicodv** [comment]
Fixed with https://github.com/nicodv/kmodes/pull/107

**Comment by ecotner** [comment]
Great, everything works now! Thank you.
