### ISSUE TITLE
Futurewarning in util/__init__.py

### ISSUE THREAD

**Issue by supreetkt** [nicodv/kmodes#110]
I receive the following warning while running kmodes:

FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  return np.vstack({tuple(row) for row in a})

**Comment by nicodv** [comment]
Thanks for the report, @supreetkt . Fixed with https://github.com/nicodv/kmodes/commit/f06831c030b789986fd755918cfd6367d7fbc452
