### ISSUE TITLE
Import kprototypes in Python3.5 takes a long time

### ISSUE THREAD

**Issue by gerasgi** [nicodv/kmodes#111]
Hi, I have an issue with importing kprototypes. I have installed it with `pip` and try to import it like this `from kmodes.kprototypes import KPrototypes `. Currently I have been waiting for 4 hours.( I tried importing it also in a script which performs a single` print("hi") ` and never made the print). Am I doing something wrong? Thank you in advance!

**Comment by nicodv** [comment]
I don't think this is specific to `kmodes`, and I've never heard of this problem before. Closing.
