### ISSUE TITLE
KPrototypes type error random_state

### ISSUE THREAD

**Issue by smiyashiro** [nicodv/kmodes#112]
Hi,
When running the following line: 
`kproto = KPrototypes(n_clusters=5, init='Huang', random_state=1234)
`

I receive this error
`TypeError: __init__() got an unexpected keyword argument 'random_state'
`

**Comment by supreetkt** [comment]
Please see [this](https://github.com/nicodv/kmodes/issues/43). `random_state` is available in the github repo via enhancements and probably not in the latest release in pypi. So if you do `pip install`, it wouldn't have the latest version. What I did was, I went into the python installation of kmodes and changed the file. You can also uninstall kmodes and [install](https://medium.freecodecamp.org/how-to-use-github-as-a-pypi-server-1c3b0d07db2) the git version of kPrototypes.

**Comment by smiyashiro** [comment]
Thanks @supreetkt! I uninstalled kmodes and then installed using `pip install git+https://github.com/nicodv/kmodes#egg=kmodes `. The random_state parameter now works.
