### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by peterzaur** [nicodv/kmodes#113]
Hi there,

Just wondering if there is a next release scheduled (0.10.0) any time soon? I'm noticing that the last release on pypi is quite behind recent activity. If it's low-lift, happy to contribute to help the release along.

Peter

**Comment by nicodv** [comment]
- Support for more than 256 clusters
- Optional parallel execution of the multiple initialization runs (courtesy of @rphes )
- Enhanced error checking when using pandas DataFrames as inputs to the algorithms
- Various bug fixes and improvements

**Comment by peterzaur** [comment]
Thanks @nicodv !
