### ISSUE TITLE
Why does cluster init ever fail with "Clustering algorithm could not initialize." when init=random?

### ISSUE THREAD

**Issue by regorsmitz** [nicodv/kmodes#115]
Assuming that n_clusters is less than the number of rows in the dataset we are inputting, why would it ever be the case that random initialization would fail? 

I'm pretty sure I am missing something because the code seems built to expect 'random' initialization to sometimes fail. Intuitively, I would think that random init should be as simple as picking [n_clusters] points from the data set at random and using them as initial centroids, so the initialization step should never fail as long as the number of points is greater than n_clusters. What am I missing? Thanks!

**Comment by nicodv** [comment]
This only happens in `kprototypes`, where what you say makes sense for the categorical variables but not when you take into consideration the numerical variables too. The centroid values for these are drawn from a normal distribution, and this can potentially lead to problems with empty clusters on initialization.
