### ISSUE TITLE
Consistency of categorical encoding of missing values

### ISSUE THREAD

**Issue by Peppejeppe** [nicodv/kmodes#120]
If the same categorical values goes across multiple dimensions, there is no consistency in the mapping.

E.g.
cols = ["origin", "Middle name", "Dog's name"]
A = ["USA", "None", "None"] can be mapped 
A = [1,0,1]

It might be convenient to have consistency, so one could ask, how many non_null values is in A after the encoding. This could be used for indexing and thus speed up calculation.

**Comment by nicodv** [comment]
I think I'm missing the point on the indexing and speed-ups. Care to elaborate, @Peppejeppe ?

**Comment by Peppejeppe** [comment]
Of cause, I will try my best. I will take focus on what I tried to implement myself.

_Example:_
I have 45000 different vectors with diffent length indicating how many registrations someone have. This varies from 1 to 45 so called attributes / features. To make the vectors even  in dimensions I used 0-padding so the people with only 1 registration, e.g. person A from my first post with only "USA", would be presented as ["USA", "None", "None",...,"None"]. I then tried to implement a self-made-dissimilarity metric, which was essentially a weighted overlap, which evaluates only the last 5 registrations before the "None", and gives higher weights to the 1st, 2nd and less to 3rd, 4th and 5th. This was not do-able because the zero-padding ("None") would be presented inconsistently by diffent integers in each attribute. In attribute 5 "None" might be mapped to the integer 0 and in attribute 6 map to the integer 5. If the categorical encoder would consistently have the same mapping through out different attributes this would allow for these kind of weighted / context based metrics. 

 _Another solution might be:_ 
Pass the encoder to the dissimilarity_methods as a parameter, and then let the user implement this themselves.

**Comment by nicodv** [comment]
If you convert all your data to integers (including the missing values), `kmodes` doesn't do any encoding. I believe that's the easiest (i.e., no code changes on `kmodes`) solution to what you're trying to do.

**Comment by Peppejeppe** [comment]
That was also the solution I ended up using. Still thought it would be a nice add-on.  

Thanks for your time.

By the way, im using this library for research purporses. Is their any particulair way it should be cited?

**Comment by nicodv** [comment]
Nice to hear. I have no preference regarding citations, @Peppejeppe .
