### ISSUE TITLE
Error: No Attributes: cluster_centroids, labels...

### ISSUE THREAD

**Issue by xinruxchen** [nicodv/kmodes#121]
Hello there, I was using the latest version of kmodes and kprototypes and tried to look at the result of cluster_cnetroids_ and labels_ but the AttributesErrors came out.
Could you go to fix it?

**Comment by nicodv** [comment]
I've enabled GitHub's bug report template feature, so closing this. Create a new issue and follow the bug reporting instructions if you still need help, @xinruxchen .
