### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'labels_'

### ISSUE THREAD

**Issue by xinruxchen** [nicodv/kmodes#122]
## Expected Behavior
I expected to have a look at the labels of each cluster.

## Actual Behavior
But got the abbritubeError:'numpy.ndarray' object has no attribute 'labels_'

## Steps to Reproduce the Problem

  1.from kmodes.kmodes import KModes
     from kmodes.kprototypes import KPrototypes
     kproto = KPrototypes(n_clusters = 2, init = "Huang")
     kp_clusters = kproto.fit_predict(data_part.values,categorical = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,    12, 13, 14, 15])
  2.kp_clusters.labels_
  3.kp_clusters.cluster_centroids_
Step 1 was good.  Got AbbributeError in Step2 and Step3.
## Specifications

  - Version: kmodes.__version__ = 0.10.0
  - Platform: windows 10

**Comment by nicodv** [comment]
`kproto.fit_predict` returns the clusters. Try doing `kproto.cluster_centroids_` instead.

**Comment by xinruxchen** [comment]
It worked. Thanks so much.
