### ISSUE TITLE
Attribute names and values mapping in cluster_centroids_

### ISSUE THREAD

**Issue by GokulVj** [nicodv/kmodes#125]
I am able to see the cluster centroids using cluster_centroids_

But I can see the attributes are not in the order in which I passed to the model. Is there a way where I could find the mapping of the attribute and value?

**Comment by nicodv** [comment]
Check out `self._enc_cluster_centroids` and `self._enc_map`. Hope that helps.

**Comment by GokulVj** [comment]
Thanks.
