### ISSUE TITLE
Unstable Centroids in KModes

### ISSUE THREAD

**Issue by yasitari** [nicodv/kmodes#131]
When I try to cluster the data with a limited number of initializations, for instance 3, they centroids vectors are not stable. I thought throughout the whole process, the mode vector is one of the training samples picked randomly, however the algorithm shows a centroid that does not exist in the training sample. For instance, If I have features A, B, C for one sample, and D, E, F for another sample, the mode vector can't be A, B, E, but that's what I get. Can you please elaborate if I misunderstood how the code functions/how this is happening?
Thank you.

**Comment by nicodv** [comment]
@yasitari , this is expected behavior. There is no guarantee (or generally any good reason) to have the centroid always be an existing data point.

**Comment by nicodv** [comment]
@yasitari , this is expected behavior. There is no guarantee that a centroid is a data point -- nor is it generally a good idea. Same goes for k-means, for example.
