### ISSUE TITLE
Supporting multi valued categorical feature for Kprototypes

### ISSUE THREAD

**Issue by maxviv** [nicodv/kmodes#133]
## Expected Behavior
Suppose I have a data-set which contains a mix of numerical and categorical features.
Suppose I have a categorical feature which is multi valued.
For example , the feature may be movie_genre which may take multiple values like {comedy, action, drama, thriller horror}.
When the encoding is done for such categorical feature, the code doesn't consider  the overlap 
between the multi valued categorical features.
For example , if a data point has genre- {action, drama}
and another data point has genre-{action, thriller}, the jaccard similarity should be taken into account
## Actual Behavior
The encoding for multivalued categorical features is done such that it considers the feature {action, thriller} separate to {thriller, action}

## Steps to Reproduce the Problem
Take any data having multi valued categorical feature and run the k-prototypes algo.
You will see that in the encoding step the categorical attributes like {action, thriller}
and {thriller, action} have been labelled differently. They are not considered same or their jaccard similarity is not taken into account
  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:

**Comment by nicodv** [comment]
@maxviv Why not simply one-hot encode these labels as new columns? E.g.:

`movie_label_comedy, movie_label_action, ...`

**Comment by maxviv** [comment]
Hi @nicodv ,
            Thanks for the reply. You are correct that I can apply one -hot encoding for my multi-valued categorical column. The example I gave you was of movie genre which has small number of unique values. This was for demonstration of the problem. But in my case the number of unique values for the multi valued categorical column can be very large depending on my design(electronic chip design). Typically it may be > 100. In such cases if I do 1 hot encoding, the dimensions will be very large and the curse of dimension  will creep in.

**Comment by nicodv** [comment]
That is inherent with your data set then. How do you imagine it can be solved by kmodes?

**Comment by maxviv** [comment]
I had tried to apply k prototypes to my data-set because my data-set consists of a mix of numerical and categorical attributes. As per the following paper:
**_[HUANG97] | (1, 2) Huang, Z.: Clustering large data sets with mixed numeric and categorical values,_** 
I thought K-Prototypes is best suited for my clustering problem

**Comment by brunobelluomini** [comment]
@srikrishna75 I had this same issue a couple minutes ago. The problem was solved after filling a categorical feature which contained null values. So I would try to inspect for null values in your dataset even for categorical features.

**Comment by nicodv** [comment]
@srikrishna75 , see the FAQ: https://github.com/nicodv/kmodes#faq

**Comment by liuyuanOUC** [comment]
Hi @nicodv, I encountered a similar problem. I use one-hot to encode the features with single value and use one-hot with multi-labels to encode the features with multiple values. The final feature vector has 14 demonstrations. E.g.: 
[
[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.]
...]

I want to use k-modes to cluster the data set, so could it can process this case?

**Comment by nicodv** [comment]
@liuyuanOUC Sure, that should not be a problem.
