### ISSUE TITLE
No module named 'kmodes.Kprototypes'

### ISSUE THREAD

**Issue by Jane419** [nicodv/kmodes#137]
## Expected Behavior
from kmodes.Kprototypes import KPrototypes

## Actual Behavior
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    from kmodes.Kprototypes import KPrototypes
ModuleNotFoundError: No module named 'kmodes.Kprototypes'

## Steps to Reproduce the Problem

  1.import kmodes
  2.from kmodes.Kprototypes import KPrototypes

## Specifications

  - Version:python3.8.0
  - Platform: windows 64

Besides, when I input "import scikit-learn", it shows "SyntaxError: invalid syntax". But I have installed scikit-learn successfully already.

**Comment by d-schmitt** [comment]
Hi @Jane419,

I noticed a lot of people are having a similar issue with importing pandas, see [here](https://github.com/pandas-dev/pandas/issues/11604). 
Do the steps provided to solve the problem help you in your case as well?

**Comment by nicodv** [comment]
Also, make sure you didn't name your working file `kmodes.py`.
