### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Chao-Tang** [nicodv/kmodes#138]
Running in to the memory error:

...
  File "C:\ProgramData\Anaconda3\lib\site-packages\kmodes\util\__init__.py", line 42, in encode_features
    Xenc = np.zeros(X.shape).astype('int')
MemoryError

Code used:

km = KModes(n_clusters=10, init='Huang', n_init=1, verbose=1,n_jobs=3)
km.fit_predict(data)

Trying to increase the n_jobs but doesn't seem to work. Data set is a csv containing clean categorical and numerical data. The file is about 43,000 rows.

**Comment by nicodv** [comment]
How many columns? That is way too few rows to have memory errors, unless you have a really small machine.

**Comment by Chao-Tang** [comment]
> How many columns? That is way too few rows to have memory errors, unless you have a really small machine.

Data set was 17 columns by 43000 rows.

Funny thing is it works perfectly in Jupyternote with the same dataset, but when I try to implement the same thing on Flask, it breaks down to the MemoryError.

**Comment by nicodv** [comment]
Errors resulting from running things inside a web server are out of scope here, so closing this.
