### ISSUE TITLE
pip install failed with error "microsoft visual c++ 14.0 is required" with python3.8

### ISSUE THREAD

**Issue by amethystzh** [nicodv/kmodes#140]
## Expected Behavior
install succeed

## Actual Behavior
pip failed with error "microsoft visual c++ 14.0 is required"

## Steps to Reproduce the Problem

  1. pip install kmodes, env as python3.8
  2. failed while install dependency scikit-learn, which don't support python3.8 yet

## Specifications

  - Version: 0.10.1
  - Platform: windows

**Comment by nicodv** [comment]
This is not specific to `kmodes`, so closing. A quick web search reveals tons of potential answers.
