### ISSUE TITLE
Categorical and Numerical Attribute difference

### ISSUE THREAD

**Issue by sin10036** [nicodv/kmodes#141]
Hi,
I have a question after doing featuring scaling in my training set. Then applying the Kprototype algorithm. How does his algorithm know the difference between numerical and categorical variables?

**Comment by nicodv** [comment]
You tell which ones are categorical with ‘categorical =[...]’

**Comment by sin10036** [comment]
Hi Nicodv,

Thanks for the quick response.I have few other questions:
1. Where do I need to specify the categorical variable?
2. If I have a ordinal categorical variable (there will be only 1 column)-Do we need to take care of this while applying Kprototype.
3. If I have a nominal categorical variable ( There will be one hot encoded vectors for that column).Do I need to specify it somewhere?

**Comment by nicodv** [comment]
1. See examples for the API (https://github.com/nicodv/kmodes/tree/master/examples)
2. Up to you to treat ordinal data as numerical or categorical.
3. You'll want to un-one-hot encode, that's what `kmodes` expects. Again, see examples.
