### ISSUE TITLE
K-Prototypes documentation contains incorrect default value

### ISSUE THREAD

**Issue by tthavendran** [nicodv/kmodes#142]
## Expected Behavior
The documentation claims `max_iter : int, default: 300`, but in reality the default value for max_iter is 100: `def __init__(self, n_clusters=8, max_iter=100, num_dissim=euclidean_dissim, cat_dissim=matching_dissim, init='Huang', n_init=10, gamma=None, verbose=0, random_state=None, n_jobs=1)`

Also, the documentation for max_iter mistakenly refers to the algorithm as K-Modes. `Maximum number of iterations of the k-modes algorithm for a single run.`

## Actual Behavior
Mentioned above.

## Steps to Reproduce the Problem

  1. Looking at documentation of K-Prototpyes
  1.
  1.

## Specifications

  - Version: 0.10.1
  - Platform:

**Comment by nicodv** [comment]
Fixed, thanks for reporting
