### ISSUE TITLE
Unable to use Jaccard similarity measures in library

### ISSUE THREAD

**Issue by etfrenchvcu** [nicodv/kmodes#143]
## Expected Behavior
jaccard_dissim_binary and jaccard_dissim_label available for use after installing library

## Actual Behavior
jaccard_dissim_binary and jaccard_dissim_label not available for use after installing library. Calling `help(kmodes.util.dissim)` only shows euclidean_dissim, matching_dissim, and ng_dissim as available for use. Any ideas why these methods would be in the code, but not in the API?

![screen](https://user-images.githubusercontent.com/37910431/74978730-3fc51a00-53fb-11ea-84d7-43e7bd88261f.png)

## Steps to Reproduce the Problem

  In a fresh Google Colab environment:
```
!pip install kmodes
import kmodes
import kmodes.util.dissim
help(kmodes.util.dissim)
```

## Specifications

  - Version: 0.10.1
  - Platform: Google Colab

**Comment by etfrenchvcu** [comment]
@BikashPandey17 This works great if I pull the code and run within the project directory. Any ideas why its not showing up when importing the library?

**Comment by BikashPandey17** [comment]
Seems like it hasn't been [released](https://github.com/nicodv/kmodes/releases) yet @nicodv, can we release it?

**Comment by nicodv** [comment]
https://github.com/nicodv/kmodes/releases/tag/0.10.2
