### ISSUE TITLE
Type of cluster_centroids_ in KModes and KPrototypes

### ISSUE THREAD

**Issue by VinceW0** [nicodv/kmodes#144]
## Expected Behavior
both return same type, either numpy.ndarray or list

## Actual Behavior
type(KModes.cluster_centroids_) returns ndarray
type(KPrototypes.cluster_centroids_) returns list

## Steps to Reproduce the Problem

As described...

## Specifications

  - Version: 0.10.2
  - Platform: Python 3.7.4

**Comment by nicodv** [comment]
Good point. I've removed this inconsistency: https://github.com/nicodv/kmodes/commit/8eabc90ebf8f7a6725af53a06211463598203de8
