### ISSUE TITLE
Distance to the nearest cluster

### ISSUE THREAD

**Issue by tinkuborah** [nicodv/kmodes#146]
Thanks for developing this module. It's been a great help.
Is it possible to get the distance of every sample to all the clusters. Logically the nearest cluster will be the one to which the sample will get assigned eventually. I have a requirement in which , when a user enters a sample , instead of assigning a label to the sample, the model should print how similar the sample is to all the clusters. This can be the distance of the sample from all the clusters.

**Comment by nicodv** [comment]
A trained `kmodes` instance will have the `.cluster_centroids_` attribute. If you use that in combination with the dissimilarity function of your choice, you can determine the distance from a point to all centroids quite easily: `dissim(centroids, curpoint)`

**Comment by ennioferreirab** [comment]
I'm  trying calculate the distances to centroids. Running the usage example.

```
data = np.random.choice(1000, (100000, 10))
km = KModes(n_clusters=10, init='Huang', n_init=5, verbose=1,n_jobs=40)
clusters = km.fit(data)
centroids = km.cluster_centroids_
clusters[0] #return 59
matching_dissim(centroids, data[0]) # return all distances iguals 10
```
The distance varies between 8-10. Almost all distances iguals 10 to every points
