### ISSUE TITLE
Better handling of NaNs

### ISSUE THREAD

**Issue by nicodv** [nicodv/kmodes#15]
`np.unique` is used for encoding data values to integers. However, `numpy` currently treats every `np.NaN` as a unique value, creating many categories. (See: https://github.com/numpy/numpy/issues/2111)

Solution is to check with `np.isnan` so that we can just ignore all NaNs when encoding. The encoder then simply assigns all NaNs to the `-1` (i.e. "I don't know this value") category.

**Comment by allefeld** [comment]
@nicodv, could you expand on this a bit, or give a code example? How does one "check with `np.isnan`" when using `np.unique`? Also, a remark in the documentation of `np.unique` would be useful.

**Comment by nicodv** [comment]
@allefeld , have a look at the commit that fixes this issue: https://github.com/nicodv/kmodes/commit/6fd7c9882886265dd1b793e17835bd7575a902c2

It basically filters out NaNs in the encoding and makes sure they get a `-1` value.
