### ISSUE TITLE
Many missing values will distort clustering

### ISSUE THREAD

**Issue by nicodv** [nicodv/kmodes#16]
Since `NaNs` are currently encoded as their own category (`-1`), they could potentially distort the clustering if there are too many of them. Is it worth it to have the dissimilarity function ignore `-1` values?

Note: this could slow down the algorithm significantly, so make sure to check for _any_ `-1` values first.

**Comment by odkken** [comment]
It's definitely tricky.  If you do ignore those values, then there's the question of whether or not you normalize the dissimilarity, since you're no longer comparing the same number of features for every data point.  I don't know how/if that would skew the clustering results.

**Comment by nicodv** [comment]
Closing, as support for missing value was dropped, in accordance with scikit-learn APIs.
