### ISSUE TITLE
Cannot handle NaN input

### ISSUE THREAD

**Issue by PascalEconomouCoupa** [nicodv/kmodes#162]
## Expected Behavior
I expected the kmodes algorithm to be able to handle missing values (```np.nan```), as described in the README.

## Actual Behavior
I get an error when the input matrix X has a missing value.

## Steps to Reproduce the Problem
``` 
import numpy as np
from kmodes.kmodes import KModes
km = KModes(n_clusters=2, init='Huang', n_init = 1, verbose=1)
X = np.array([[np.nan, 1], [0, 1], [0, 0]])
km.fit_predict(X)
```
Output:
```
~/.local/lib/python3.7/site-packages/sklearn/utils/validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

## Specifications

  - Version: kmodes 0.11.0, scikit-learn 0.24.2
  - Platform: remote JupyterHub

**Comment by nicodv** [comment]
Looks like sklearn has update their data validation. Since `kmodes` tries to follow the sklearn interface and behavior where possible, I'm hereby essentially dropping support for NaNs.

I will update the documentation accordingly.
