### ISSUE TITLE
Running kprototype with all numerical features?

### ISSUE THREAD

**Issue by akash-suresh** [nicodv/kmodes#17]
By giving category list as empty i.e. []. It raises an error. Any work arounds?

**Comment by nicodv** [comment]
Please post the error you're getting, and I'll have a look.

Note that without categorical variables, you're effectively doing k-means that way, and there's a better solution for that: http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

**Comment by akash-suresh** [comment]
Yes. I agree I can use the Kmeans from scikit learn. But is it possible to run kprototypes for the same as well?

**Comment by nicodv** [comment]
Again, please post the error you're getting, and I'll have a look.

**Comment by akash-suresh** [comment]
Hey the code is.

```
def kp_cluster(df,cat_list,n_c):
    X = np.array(df)
    kproto = kprototypes.KPrototypes(n_clusters=n_c, init='Cao', verbose=1, n_init=10)
    clusters = kproto.fit_predict(X, categorical=cat_list)
    return clusters,kproto.cost_
```
```
cat_list=[]
labels,cost = kp_cluster(b,cat_list,6)
```
the data, b is 
```
      0
0   0.0
1   0.0
2   0.0
3   0.0
4  -0.5
5  -0.5
6   0.0
7   0.0
8   0.0
9   0.0
10  0.0
11  0.0
12  0.5
13 -0.5
14  0.5
15  0.5
16  0.0
17  0.5
18  0.0
19 -0.5
20  0.0
21  0.0
22  0.0
23  0.0
24  0.0
```

This is the error.

<img width="1106" alt="screen shot 2016-06-16 at 10 05 24 am" src="https://cloud.githubusercontent.com/assets/10497294/16105691/6084677a-33aa-11e6-814b-b63d26ba942d.png">

**Comment by nicodv** [comment]
This is too much work to fix, since the assumption of categorical data is deeply rooted into the k-prototypes code (for good reason).

Whenever a user does not present categorical variables, k-prototypes now raises a NotImplementedError with tips on what to do next (i.e., either choose categorical columns, or use k-means).
