### ISSUE TITLE
Performance over binary data

### ISSUE THREAD

**Issue by ale94mleon** [nicodv/kmodes#172]
I need to cluster binary vectors, I am currently using kmodes. I have been consulting the bibliography and there are a zoo of methods for categorical data classification and Kmodes is one of the most recommended. **My question**: Is kmodes still good for binary data, is there some review (paper) for documentation on this?
In some how binary data is categorical data, but I am still a little confuse after been reading for a whole day about clustering :-\
Thank you so much for any feedback.

**Comment by nicodv** [comment]
This is a very broad, theoretical question that is way outside the scope of the `kmodes` issue tracker, hence closing.

I think you can use `kmodes` without any problem, but I can't weigh in on whether it's the best choice for your particular data set and use case.
