### ISSUE TITLE
parallelization

### ISSUE THREAD

**Issue by KhatriVivek** [nicodv/kmodes#173]
Would it be possible to modify the below code and illustrate for parallel computing on several cores

import numpy as np
from kmodes.kmodes import KModes

# random categorical data
data = np.random.choice(20, (100, 10))

km = KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_

**Comment by nicodv** [comment]
Parallelization over multiple initializations is already possible: https://github.com/nicodv/kmodes#parallel-execution

**Comment by KhatriVivek** [comment]
Thanks. I did see that. I am more familiar with R than Python, and if it
was an easy change, I was asking for help

**Comment by nicodv** [comment]
Yeah, so just change it to:

    km = KModes(n_clusters=4, init='Huang', n_init=5, n_jobs=<minimum of number of cores or n_init here>, verbose=1)

**Comment by KhatriVivek** [comment]
Excellent. Thank you so much
