### ISSUE TITLE
kprototype gets stuck in loops.

### ISSUE THREAD

**Issue by akash-suresh** [nicodv/kmodes#18]
This is the data I am passing 

![image](https://cloud.githubusercontent.com/assets/10497294/16077136/9ceed34e-3314-11e6-9ef3-b7695d56c82a.png)

Below is my cluster function.

```
def kp_cluster(df,cat_list,n_c):
    X = np.array(df)
    kproto = kprototypes.KPrototypes(n_clusters=n_c, init='Cao', verbose=1, n_init=10)
    clusters = kproto.fit_predict(X, categorical=cat_list)
    return clusters,kproto.cost_
```

Here is the cluster call - 

`        labels,cost = kp_cluster(data,cat_list,n)
`

where, cat_list = [1] and n = 6.

It goes on printing 

Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters

over and over till it crashes my ipython notebook.

**Comment by nicodv** [comment]
This is probably related to https://github.com/nicodv/kmodes/issues/6.

I'll use your data set to try and reproduce the problem.

**Comment by akash-suresh** [comment]
How do we set how long it can take to initialize?

are you referring to n_init or max_iter?

**Comment by nicodv** [comment]
> How do we set how long it can take to initialize?

Not possible presently, but something along those lines is what should be added to avoid this problem.

**Comment by akash-suresh** [comment]
Could you just reproduce the problem and try helping me out. I have to get this done by the end of the day. 

Thanks for all the help 👍

**Comment by akash-suresh** [comment]
Here is the data.

[op.csv.zip](https://github.com/nicodv/kmodes/files/317789/op.csv.zip)

**Comment by nicodv** [comment]
Thanks, I've used the data to add a test for this situation. This, and its duplicate (https://github.com/nicodv/kmodes/issues/6) are now fixed.

**Comment by akash-suresh** [comment]
What was the situation? Could you throw some light on this?

**Comment by nicodv** [comment]
The deterministic initialization (Cao's method) could not find good initial clusters. I now let the algo switch to random initialization after a while when this occurs, and raise an initialization error if it keeps occurring after even more attempts.

**Comment by akash-suresh** [comment]
Oh alright. Thanks for your help man. Much appreciated 👍
