### ISSUE TITLE
Please add conda installation information

### ISSUE THREAD

**Issue by sugatoray** [nicodv/kmodes#182]
`kmodes` can be installed with `conda` from `conda-forge` channel. Please add that to your methods of installation in README. 

```sh
conda install -c conda-forge kmodes
```

Alternatively, if you have `mamba` installed in the same conda environment, just replace `conda` with `mamba` in the command above to get a quicker installation.

```sh
# conda install -c conda-forge mamba
mamba install -c conda-forge kmodes
```

Source: 
 - https://anaconda.org/conda-forge/kmodes
 - https://github.com/conda-forge/kmodes-feedstock

**Comment by nicodv** [comment]
Ah, that explains why the no. of monthly downloads took a huge jump upwards.

Updated the README in https://github.com/nicodv/kmodes/commit/66c4dffa2fe7a35a5fe52abf1159c93dbfe346e3

Thanks for reporting, @sugatoray !
