### ISSUE TITLE
Different clusters when K-Prototypes trained on same data in numpy array and pandas dataframe

### ISSUE THREAD

**Issue by RoddyJaques** [nicodv/kmodes#183]
I'm getting very different results when using fit_predict() on a KPrototypes wiht the same dataset as a pandas dataframe and numpy array.

The resulting clusters are very different, I've kept random_state constant, the only difference is the format of the input data. Have checked dtypes and all are consistent.

**Comment by nicodv** [comment]
I added tests for this scenario, but I can't reproduce this: https://github.com/nicodv/kmodes/commit/f5532e0064207aab4edcb53be509153aa2cf00ac

Please provide a fully reproducible example, @RoddyJaques .
