### ISSUE TITLE
Not an issue. So much as a doubt. 

### ISSUE THREAD

**Issue by akash-suresh** [nicodv/kmodes#19]
When I pass some data to kmeans and give number of clusters as 6. (Knowing the best fit is 3 clusters). 
Kmeans actually clusters it into only 3 clusters. Overriding my number of clusters. 

Do you know how and why this happens? 

And also why the kprototypes, though based from kmeans doesn't work the same way?

**Comment by nicodv** [comment]
Are you using the same data you showed me earlier? That only had 3 unique numerical values, so the algorithm might be smart enough to ignore your silly input of 6.

**Comment by akash-suresh** [comment]
Yes the same data. It had only three numerical values. 

Yes. Exactly my question. How can the algorithm wrap it's head around this? 

Isn't it supposed to initialize 6 centroids and go on as traditional methods do? (The scikit-learn kmeans module btw)

**Comment by nicodv** [comment]
Not that surprising that it quickly scans the data for no. of unique values, no? That makes the clustering obvious, and no algorithm is necessary.

**Comment by akash-suresh** [comment]
Can this be implemented in the kprototypes as well?

**Comment by nicodv** [comment]
Good idea. See https://github.com/nicodv/kmodes/issues/20

**Comment by akash-suresh** [comment]
👍
