### ISSUE TITLE
[BUG] Badge not rendering in readme

### ISSUE THREAD

**Issue by darigovresearch** [nicodv/kmodes#192]
## Expected Behavior
Conda badge to render

## Actual Behavior
![image](https://user-images.githubusercontent.com/30328618/206861710-7859855f-2ff8-49eb-b338-a5cfdcf68cad.png)

**Comment by nicodv** [comment]
Fixed by https://github.com/nicodv/kmodes/commit/7481a88841e67d99d47287ea7b8a36f4a14d5344

**Comment by darigovresearch** [comment]
Thanks for the fix @nicodv !
