### ISSUE TITLE
Incorrect dtype conversion of categoricals when dealing with manually assigned centroids

### ISSUE THREAD

**Issue by susmitpy** [nicodv/kmodes#193]
## Expected Behavior
With respect to, KPrototypes, whenever ```init``` is passed as a - list of lists with length 2. The second list which is supposed to be the initial centroid of categorical columns should be an array of string

## Actual Behavior
The second list is is converted into dtype uint8
The offending lines are,
https://github.com/nicodv/kmodes/blob/master/kmodes/kprototypes.py#L359-L360

            centroids = [np.asarray(init[0], dtype=np.float64), 
                          np.asarray(init[1], dtype=np.uint16)]

## Steps to Reproduce the Problem

  1. Pass init as [[65], ["A"]] , with categorical_idxs = [1]
data passed is for fitting the model on: [[65, "A"]]

## Specifications

  - Version: 0.12.2
  - Platform: Macos

**Comment by nicodv** [comment]
The initial values should be encoded categorical values, actually. See this test with an example: https://github.com/nicodv/kmodes/blob/master/kmodes/tests/test_kprototypes.py#L161-L173

You can get the encoding from `self._enc_map` from a fitted model, and in kmodes.util` there's an `encode_features` function.

**Comment by susmitpy** [comment]
Got it. Thanks.

**Comment by susmitpy** [comment]
Got it. Thanks !
