### ISSUE TITLE
What do centroids mean and how are they computed?

### ISSUE THREAD

**Issue by BrazilForever11** [nicodv/kmodes#25]
Here is my code:

```
import numpy as np
from kmodes import kmodes

x = np.genfromtxt('custom.csv', dtype=str, delimiter=',')

kmodes_huang = kmodes.KModes(n_clusters=2, init='Huang', verbose=1)
kmodes_huang.fit(x)

# Print cluster centroids of the trained model.
print(kmodes_huang.cluster_centroids_)
# Print training statistics
print('Final training cost: {}'.format(kmodes_huang.cost_))
print('Training iterations: {}'.format(kmodes_huang.n_iter_))
```

Here is output:

```

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 0, cost: 10.0
[[2 0]
 [6 2]]
Final training cost: 10.0
Training iterations: 1


```
Here is file with data (I had to change extension to .txt)
[custom.txt](https://github.com/nicodv/kmodes/files/480985/custom.txt)

How should I interpret centroids? Would it be better to output medoids instead? Are you implicitly imbeding everything in R^n and using Eucleadian metric to find centroids?

**Comment by nicodv** [comment]
Internally, I encode all you color categories into integers for speed. That's why you see [[2, 0], [6, 2]] instead of color names. Have a look at `kmodes_huang.enc_map_` for interpretation of those integers.

I don't use Euclidean distance in kmodes, but determine in how many dimension the colors match (matching dissimilarity). See the papers mentioned in README for details.

**Comment by BrazilForever11** [comment]
Thank you for clarification! Is there function to decode it quickly? It seems like scikit preprocessing.LabelEncode does something similar.

**Comment by nicodv** [comment]
Your comment about decoding made me think... `cluster_centroids_` now shows the decoded centroids with the original data labels.

I enabled this by making `cluster|_centroids_` a computed property that decodes the internally used `_enc_cluster_centroids` (formerly known as `cluster_centroids_` using `_enc_map` (both now hidden properties).
