### ISSUE TITLE
Manual centroid initialization for k prototypes clustering

### ISSUE THREAD

**Issue by Hari001** [nicodv/kmodes#27]
If the dataset has only one numerical variable, then manual initialization of centroids never works as the condition checks always fail. In this case, if  `init` is the initialization vector,`init[0]` is a 1D vector and so `shape[1]` gives an error.

**Comment by nicodv** [comment]
Internally, I now use np.atleast_2d to present the N initial values as a 2-dimensional array with size [N, 1]. I've also implemented more checks and tests for manual initialization.
