### ISSUE TITLE
Keep getting an Error - please help

### ISSUE THREAD

**Issue by roshenw** [nicodv/kmodes#31]
Hi, 
Im trying write a program to cluster some user click data. I keep getting this error and I cant seem to figure out how to fix it. I have not done any ML in the past, so dont fully understand what effect each variable here has.  Please help.

**This is the script I used**
`import numpy as np
from kmodes import kprototypes

syms = np.genfromtxt('mlog1day_top100.csv', dtype=str, delimiter=',')[:, 0]
X = np.genfromtxt('mlog1day_top100.csv', dtype=object, delimiter=',')[:, 1:3]

X[:, 0] = X[:, 0].astype(float)
X[:, 1] = X[:, 1].astype(float)
X[:, 2] = X[:, 2].astype(str)
X[:, 3] = X[:, 3].astype(str)

kproto = kprototypes.KPrototypes(n_clusters=4, init='Cao', verbose=2)
clusters = kproto.fit_predict(X, categorical=[1, 2])

print(kproto.cluster_centroids_)

print(kproto.cost_)
print(kproto.n_iter_)

for s, c in zip(syms, clusters):
    print("Symbol: {}, cluster:{}".format(s, c))`

**This is what the input data looks like:**  
5 comma seperated columns
`
64870551, 3223,5, /offerId/759152/uSource/MGS,GoShop 

80729030,889,3, /offerId/729119/categoryId/0/usource/STROFDEF,OfferDetail

66257932,129,5, /offerId/759120/categoryId/424/subCategoryId/0/uSource/CPTS,OfferDetail

85135356,3014,1, /uSource/hnmnu/product/vacations,Travel home page

74661688,396,1, /offerid/358634/uSource/PTMTILE,OfferDetail

84572627,3898,2, /product/hotels,Travel home page

75163088,138,2, /offerid/759057,OfferDetail
`

**This is the error that I keep getting:**

`Initialization method and algorithm are deterministic. Setting n_init to 1.
Traceback (most recent call last):
  File "stocks.py", line 18, in <module>
    clusters = kproto.fit_predict(X, categorical=[1, 2])
  File "/Users/rweliwatta/anaconda/lib/python2.7/site-packages/kmodes/kmodes.py", line 345, in fit_predict
    return self.fit(X, **kwargs).labels_
  File "/Users/rweliwatta/anaconda/lib/python2.7/site-packages/kmodes/kprototypes.py", line 353, in fit
    self.verbose)
  File "/Users/rweliwatta/anaconda/lib/python2.7/site-packages/kmodes/kprototypes.py", line 134, in k_prototypes
    "All columns are categorical, use k-modes instead of k-prototypes."
AssertionError: All columns are categorical, use k-modes instead of k-prototypes.`

Any help is really appreciated. 

Thank you, 
Roshen

**Comment by nicodv** [comment]
Maybe you're getting your data shapes messed up.  With `X = np.genfromtxt('mlog1day_top100.csv', dtype=object, delimiter=',')[:, 1:3]`, you're selecting columns 1 and 2 from your original data. `X` is now an N x 2 column, and `X[:, 2] = X[:, 2].astype(str)` should have failed already.

Note that the `categorical=[1, 2]` option is to let the algorithm know that the second and third columns should be interpreted as categorical, and all other columns as numerical. If you're using all data columns, this would read `categorical=[2, 3]` in the example you give.
