### ISSUE TITLE
Jaccard dissimilarity measure

### ISSUE THREAD

**Issue by chrisjluc** [nicodv/kmodes#36]
Are we adding a jaccard dissimilary measure?

**Comment by nicodv** [comment]
Seems easy enough to implement. PRs are welcome. :)

Note that `k-modes` 0.7 offers support for custom dissimilarity measures, so you can already use it if you have your own implementation: https://github.com/nicodv/kmodes/blob/master/kmodes/kmodes.py#L289

**Comment by BikashPandey17** [comment]
I have been working on the jaccard dissimilarity algorithm and I came up with the functions to use with Kmodes. Is there a way to contribute to the project.

**Comment by nicodv** [comment]
@BikashPandey17  Sure, see here: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by nicodv** [comment]
https://github.com/nicodv/kmodes/pull/129 was merged, adding binary and multi-label versions of Jaccard dissimilarity.
