### ISSUE TITLE
Add dissimilarity measure from Ng et al. (2007)

### ISSUE THREAD

**Issue by nicodv** [nicodv/kmodes#37]
The dissimilarity measure supposedly improves convergence. Well-cited paper, too.

http://ieeexplore.ieee.org/abstract/document/4069266/

**Comment by benandow** [comment]
I implemented this for a prior project. Sent a PR. Feel free to merge into the main branch.

Best,
-Ben

**Comment by nicodv** [comment]
Merged: https://github.com/nicodv/kmodes/pull/52
