### ISSUE TITLE
Can't build package: AttributeError: module 'kmodes' has no attribute '__version__'

### ISSUE THREAD

**Issue by bdwinter10** [nicodv/kmodes#42]
Hello,
I also tried using python script to install the package: python setup.py install.  However, I get the error message:
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    VERSION = kmodes.__version__
AttributeError: module 'kmodes' has no attribute '__version__'

**Comment by nicodv** [comment]
I'm afraid I can't reproduce this. Can you give more detail about your setup and what you did exactly?
