### ISSUE TITLE
'random_state' parameter for Kmodes

### ISSUE THREAD

**Issue by Nishanth14** [nicodv/kmodes#43]
KModes is returning  different results each time for the same data set. I don't see parameter 'random_state' to resolve the issue. Is there any way to make KModes to be consistent.

**Comment by nicodv** [comment]
Yes there is. Set the random seed for numpy:

`np.random.seed(42)`

**Comment by Nishanth14** [comment]
Thanks! it worked.

**Comment by supreetkt** [comment]
Hi, I'm trying this, but it isn't letting me set the seed saying 'no random_state parameter'. And if I set the seed program-wide, the results change each time.

**Comment by supreetkt** [comment]
Hi, I have a similar issue. I'm able to set a random_state parameter, but it isn't working as a seed. The results change with each run anyway.

**Comment by nicodv** [comment]
@supreetkt , could you present a minimal reproducible example?

**Comment by supreetkt** [comment]
Okay, I think I was wrong. I'm not able to set the seed.kmodes_seed = 123
`km = KModes(n_clusters=k, init='Huang', n_init=5)
model = km.fit(m_array, random_state=kmodes_seed)
predictions_lst = model.labels_.tolist()`

The predictions here are changing with each run.

**Comment by supreetkt** [comment]
Okay. I made a copy of the repo from github and then tried running it, it didn't cause a problem to use random_state. Seems like when you install kmodes with `pip install`, it still doesn't have the random_state parameter.

**Comment by supreetkt** [comment]
Okay, I figured it out. I had installed kmodes with `pip install` and somehow it still contained the previous version where `random_state` was not available as a parameter. I updated the file and it is working now.

**Comment by nicodv** [comment]
OK, great. Yes, that feature will be in the next release.
