### ISSUE TITLE
KPrototypes fit_predict error: "could not convert string to float"

### ISSUE THREAD

**Issue by wa1618i** [nicodv/kmodes#47]
I want to apply Kprototype into my dataset but it seems that the code can't convert into numpy arrays?
km = kprototypes.KPrototypes(n_clusters=10, init='Cao', verbose=2)
train=pd.read_csv('/home/lemma/train.csv')
train['clusters_KModes'] = km.fit_predict(train1,categorical=[1])
ValueError: could not convert string to float: MJ

Trying to convert into object to match the example given also not successful:
km = kprototypes.KPrototypes(n_clusters=10, init='Cao', verbose=2)
train=pd.read_csv('/home/lemma/train.csv')
train1=train1.values.astype(object)
train['clusters_KModes'] = km.fit_predict(train1,categorical=[1])
ValueError: could not convert string to float: MJ

**Comment by nicodv** [comment]
Could you post the full traceback, so I can see where the error occurs exactly?

Also, what does your data look like?

**Comment by wa1618i** [comment]
Sorry for late reply. My data contains both numerical (0.xxx)and categorical of one and two alphabet (A,B,XZ). Here is the snippet:

km = kprototypes.KPrototypes(n_clusters=10, init='Cao', verbose=2)
train1=pd.read_csv('/home/lemma/train.csv')
train1=train1.drop(['id','loss'],1)
train1=train1.values.astype(object)
train1['clusters_KModes'] = km.fit_predict(train1,categorical=[1,2,3])
![image](https://user-images.githubusercontent.com/26052229/28240015-49b5b8a2-69a3-11e7-922e-4be7f0a457e8.png)

**Comment by nicodv** [comment]
With `categorical=[1,2,3]`, you're telling the algorithm that the second, third and fourth columns are categorical. But from your screenshot it looks like there's many more categorical variables. That why kmodes is trying to interpret the 'MJ' string as a float.

**Comment by wa1618i** [comment]
Hi categorical=[1,2,3] is just for snipped only, The actual categorical written in python is ranging from 1-116. Ok so I need to do treatment for categorical data because MJ, EG, etc...cannot be converted into float.
