### ISSUE TITLE
What happens when gamma is set to 0?

### ISSUE THREAD

**Issue by ygate** [nicodv/kmodes#51]
My understanding is that setting gamma to 0 is like running K-Means on the data because the categorical similarity will always be elementated. However, the results are different than sklearn's K-Means. Am I missing something?

**Comment by nicodv** [comment]
I haven't compared my implementation to sklearn's, so I'm not sure.

A huge potential difference between the two is that sklearn uses the powerful k-means++ initialization method by default. Are the results still very different when you use `init='random'` in sklearn?

**Comment by ygate** [comment]
I am in the process of confirming that. Just to make sure, the catigorical part will not have any impact when gamma is set to 0?

**Comment by nicodv** [comment]
Correct

**Comment by sharma-ji** [comment]
Just for curiosity, what is the range of gamma ?

**Comment by nicodv** [comment]
@sharma-ji , from 0 (i.e. you're effectively doing k-means) to infinite-ish (i.e. you're effectively doing k-modes).
