### ISSUE TITLE
AttributeError on import

### ISSUE THREAD

**Issue by islaywright** [nicodv/kmodes#54]
Hi,
I have no trouble importing kmodes. However, when I run the example from the README:
```
import numpy as np
from kmodes import kmodes

# random categorical data
data = np.random.choice(20, (100, 10))

km = kmodes.KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

```
I get the following error:
AttributeError: module 'kmodes.kmodes' has no attribute 'KModes'

Do you know why this is happening? I have cloned the most recent master branch and am building from this.

**Comment by nicodv** [comment]
That's probably due to some conflict between the root `kmodes` package and the newly imported `kmodes` module. Try this instead:

```
from kmodes.kmodes import KModes
KModes(...)
```
