### ISSUE TITLE
pip Installation Errors

### ISSUE THREAD

**Issue by salcedam** [nicodv/kmodes#55]
When I tried installing kmodes via pip, it would fail to install. I've attached the error log. To install it properly, I built it directly from source. I'm assuming the pypi version is not updated with the latest which is why it's failing to install?
[error.txt](https://github.com/nicodv/kmodes/files/1325455/error.txt)

**Comment by bcthomas** [comment]
I am guessing this is the same problem as in #48

**Comment by nicodv** [comment]
Looks like scikit-learn failed to install. Googling gave me this: https://stackoverflow.com/questions/42360126/error-while-trying-to-install-sklearn-from-pycharm-arrayobject-h-cannot-be-abs

Better check here for help: https://github.com/scikit-learn/scikit-learn/issues
