### ISSUE TITLE
Get costs at any given iteration

### ISSUE THREAD

**Issue by daffidwilde** [nicodv/kmodes#59]
I want to visualise the convergence rate of k-modes (and k-prototypes, eventually) by plotting the cost function at each iteration. I've had a look through `kmodes.py` and I can't see a way of extracting that information directly. Could you suggest a way of going about this? 

Thanks,

Henry

**Comment by nicodv** [comment]
This is not currently supported, but should be an easy fix.

See here: https://github.com/nicodv/kmodes/blob/master/kmodes/kmodes.py#L274

In stead of just storing `all_costs[best]`, we could also store `all_costs`.

Feel free to make a PR.

**Comment by daffidwilde** [comment]
What I actually mean is that I want to visualise the cost at each epoch within a single run of the algorithm, not just the final cost. Apologies if I am mistaken.

**Comment by daffidwilde** [comment]
Fixed as of #79.
