### ISSUE TITLE
K-protoypes can get stuck in initialization

### ISSUE THREAD

**Issue by nicodv** [nicodv/kmodes#6]
K-protoypes can get stuck in initialization if it never reaches the point where there are no more empty clusters.

Set a maximum to how long it can initialize and warn the user of the problem.

**Comment by paulaceccon** [comment]
I'm forcing the init to be random but it stays stuck the same way.

```
kproto = KPrototypes(n_clusters=4, init='random', verbose=1)
clusters = kproto.fit_predict(df.values, categorical=list(df.columns.get_indexer_for(categorical)))
```

**Comment by nicodv** [comment]
Random often is a poor choice. Any reason you're doing that instead of using `huang`/`cao`?
