### ISSUE TITLE
-1 in _enc_cluster_centroids[1]

### ISSUE THREAD

**Issue by ShrishtiAK** [nicodv/kmodes#61]
What does -1 depict in this array

**Comment by ShrishtiAK** [comment]
Hi,
I am getting a key error: -1 on accessing the centroids while running kprototypes. On checking, I found that there is a -1 value in _enc_cluster_centroids[1] which can't be decided back. In what case does -1 appear as a centroid feature? 

Thanks

**Comment by nicodv** [comment]
This happens in case of missing data. See the README for more explanation. It's suggested you fill the missing values first.
