### ISSUE TITLE
Failure in prediction

### ISSUE THREAD

**Issue by yueguoguo** [nicodv/kmodes#62]
Hi I am using the trained clustering model for prediction, and sometimes it failed with error message of 
`axis 1 is out of bounds for array of dimension 0`
Just curious if anyone has encountered any similar errrors.

The data I am working on has 7.5M rows and 6 columns. All of the variables are categorical with equal or less than 5 levels.

**Comment by nicodv** [comment]
@yueguoguo Please include the complete traceback so we can locate the bug.

**Comment by yueguoguo** [comment]
Hi @nicodv thanks for reply. I was just reproducing the very example you provided, i.e., 
```
import numpy as np
from kmodes.kmodes import KModes

# random categorical data
data = my_data

km = KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(my_data)
```
Then I used the model method `km.predict` for clustering on new data (same schema with the one used for training), and got the error as shown above. 

Apologize I cannot disclose any more about the data as it is confidential. Just would like to know if there is anyone ever had similar issue. Strangely it worked sometimes...

**Comment by PabloVergara** [comment]
Hi nicodv!
I have a similar problem when I try using the trained clustering model for predic data with the same scheme used for training, I can not even predict even using the same training set. 
I'm also using init = Cao.

kp = KPrototypes(n_clusters = nc, init = 'Cao', n_init =50, verbose = 1, random_state=4, n_jobs=8 )
clusters=kp.fit_predict(data.values, categorical = [9])

the first error that came back to me was the following: 


```
Traceback (most recent call last):

  File "<ipython-input-50-bfb03da94a9c>", line 1, in <module>
    kp.predict(data)

  File "C:\Users\pneira\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes\kprototypes.py", line 467, in predict
    Xnum, Xcat = _split_num_cat(X, categorical)

  File "C:\Users\pneira\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes\kprototypes.py", line 46, in _split_num_cat
    Xnum = np.asanyarray(X[:, [ii for ii in range(X.shape[1])

AttributeError: module 'dfply.data' has no attribute 'shape'

```
then change that line for "np.shape (X) [1]"
![Captura3](https://user-images.githubusercontent.com/24994152/57384630-f0b93b80-717e-11e9-8f94-8d92dbd08065.PNG)

and the next thing happened when I run the algorithm again


```
Traceback (most recent call last):

  File "<ipython-input-52-bfb03da94a9c>", line 1, in <module>
    kp.predict(data)

  File "C:\Users\pneira\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes\kprototypes.py", line 467, in predict
    Xnum, Xcat = _split_num_cat(X, categorical)

  File "C:\Users\pneira\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes\kprototypes.py", line 46, in _split_num_cat
    Xnum = np.asanyarray(X[:, [ii for ii in range(np.shape(X)[1])

  File "C:\Users\pneira\AppData\Local\Continuum\anaconda3\lib\site-packages\kmodes\kprototypes.py", line 47, in <listcomp>
    if ii not in categorical]]).astype(np.float64)

TypeError: argument of type 'NoneType' is not iterable`

```

**Comment by PabloVergara** [comment]
I managed to solve it, I just had to indicate the categorical variables
eg:
 kp.predict (data, categorical = [1,2,3,])
