### ISSUE TITLE
Summed dissimilarity measure in Cao's method

### ISSUE THREAD

**Issue by daffidwilde** [nicodv/kmodes#65]
### Hello, and apologies for the long issue...

My name is Henry Wilde and I am a PhD student at Cardiff University. I am currently working on a research project involving the k-modes and k-prototypes algorithms and have been using this implementation of the algorithms to compute my results. In particular, I have been looking at the initialisation processes to the k-modes algorithm. Whilst reading Cao's original [paper](https://pdfs.semanticscholar.org/1955/c6801bca5e95a44e70ce14180f00fd3e55b8.pdf) alongside the source code for this implementation, I believe that I have found an error in the implementation of Cao's method (and potentially Huang's as well) due to the wrong dissimilarity measure being used. I have a working implementation locally, and hope it would be alright to open a pull request for these changes. I've detailed where I believe the issue to be below, and have given a small working example to highlight the difference.

The paper, and other papers (such as [Huang's](http://arbor.ee.ntu.edu.tw/~chyun/dmpaper/huanet98.pdf)), define the standard dissimilarity measure between two points to be the number of attributes where the two points are not equal. Then, separately, the summed dissimilarity of a point in the dataset is the sum of all the pairwise dissimilarities between the point of interest and all other points in the dataset. There are definitions for these two measures and for the average density of a point [here](https://drive.google.com/open?id=16SfhcuxGmCbSo70ek2NPZYe3lwZ322BZ).

In this implementation, I believe that the summed dissimilarity measure is used where the pairwise dissimilarity measure should be used (a full statement of the algorithm is given [here](https://drive.google.com/open?id=1xnzp-mZh-MZwKdXi_omtIwKVTqnrGz0v)), and that is leading to incorrect initialisations. 

### A small example below highlights this:

Consider the following dataset with N=10 elements described by m=5 attributes: 

- Buying price 
- Maintenance costs
- No. doors
- No. passengers
- No. wheels

The first two attributes take values from L, M, H, V standing for low, medium, high, and very high, respectively. The other three attributes are integer variables and are considered to be categorical.

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Buying price</th>      <th>Maintenance costs</th>      <th>No. doors</th>      <th>No. passengers</th>      <th>No. wheels</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>H</td>      <td>M</td>      <td>2</td>      <td>2</td>      <td>4</td>    </tr>    <tr>      <th>1</th>      <td>L</td>      <td>M</td>      <td>0</td>      <td>1</td>      <td>2</td>    </tr>    <tr>      <th>2</th>      <td>V</td>      <td>H</td>      <td>2</td>      <td>3</td>      <td>8</td>    </tr>    <tr>      <th>3</th>      <td>H</td>      <td>L</td>      <td>4</td>      <td>5</td>      <td>4</td>    </tr>    <tr>      <th>4</th>      <td>M</td>      <td>M</td>      <td>2</td>      <td>5</td>      <td>4</td>    </tr>    <tr>      <th>5</th>      <td>M</td>      <td>L</td>      <td>2</td>      <td>4</td>      <td>4</td>    </tr>    <tr>      <th>6</th>      <td>V</td>      <td>H</td>      <td>4</td>      <td>5</td>      <td>4</td>    </tr>    <tr>      <th>7</th>      <td>L</td>      <td>V</td>      <td>2</td>      <td>4</td>      <td>4</td>    </tr>    <tr>      <th>8</th>      <td>H</td>      <td>M</td>      <td>0</td>      <td>2</td>      <td>2</td>    </tr>    <tr>      <th>9</th>      <td>H</td>      <td>M</td>      <td>4</td>      <td>7</td>      <td>4</td>    </tr>  </tbody></table>

Suppose we wish to cluster this dataset into 3 parts. To initialise this dataset for clustering with the k-modes algorithm by Cao's method, we begin by finding the average density of each point in our set. This is given in the last column of the following table:

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Buying price</th>      <th>Maintenance costs</th>      <th>No. doors</th>      <th>No. passengers</th>      <th>No. wheels</th>      <th>Density</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>H</td>      <td>M</td>      <td>2</td>      <td>2</td>      <td>4</td>      <td>0.46</td>    </tr>    <tr>      <th>1</th>      <td>L</td>      <td>M</td>      <td>0</td>      <td>1</td>      <td>2</td>      <td>0.24</td>    </tr>    <tr>      <th>2</th>      <td>V</td>      <td>H</td>      <td>2</td>      <td>3</td>      <td>8</td>      <td>0.22</td>    </tr>    <tr>      <th>3</th>      <td>H</td>      <td>L</td>      <td>4</td>      <td>5</td>      <td>4</td>      <td>0.38</td>    </tr>    <tr>      <th>4</th>      <td>M</td>      <td>M</td>      <td>2</td>      <td>5</td>      <td>4</td>      <td>0.44</td>    </tr>    <tr>      <th>5</th>      <td>M</td>      <td>L</td>      <td>2</td>      <td>4</td>      <td>4</td>      <td>0.36</td>    </tr>    <tr>      <th>6</th>      <td>V</td>      <td>H</td>      <td>4</td>      <td>5</td>      <td>4</td>      <td>0.34</td>    </tr>    <tr>      <th>7</th>      <td>L</td>      <td>V</td>      <td>2</td>      <td>4</td>      <td>4</td>      <td>0.34</td>    </tr>    <tr>      <th>8</th>      <td>H</td>      <td>M</td>      <td>0</td>      <td>2</td>      <td>2</td>      <td>0.30</td>    </tr>    <tr>      <th>9</th>      <td>H</td>      <td>M</td>      <td>4</td>      <td>7</td>      <td>4</td>      <td>0.40</td>    </tr>  </tbody></table>

With the current implementation for Cao's method, row 0 is correctly identified as the point with maximal density and made the first centroid in the initialisation. However, the second and third initial centroids are also chosen as the first point in the set.

```python
>>> from kmodes.kmodes import init_cao
>>> X = vehicle_data.values
>>> init_cao(X, 3)
array([['H', 'M', 2, 2, 4],
       ['H', 'M', 2, 2, 4],
       ['H', 'M', 2, 2, 4]], dtype=object)
```

It follows from the statement of Cao's method that the point to be selected as the second centroid should have the maximal product of density and distance from our first centroid. Therefore, since there are no duplicate rows in our set, and the dissimilarity between any point and itself is zero, we should not see the same point chosen twice. In fact, if we look at the pairwise dissimilarity between all the points and our first centroid we see that rows 1, 2 and 6 have maximal dissimilarity (equal to 4), and of those rows - using our second table - we see that row 6 has maximal density. Hence, this is our second centroid.

Now,  we use a similar technique, following the statement of the algorithm, to find our third centroid. We must find which of our two centroids has minimal density * dissimilarity for each of our points, and then take the point in our set which has the maximal value of these minima. This point can be found by constructing a 2 x 10 matrix (indexed from 0) where the (i,j)th entry is the density of row i multiplied by the dissimilarity of row i with centroid j. This point corresponds to row 5.

So, we should expect our centroids to be given by row 0, row 6 and row 5.

My altered implementation of Cao's method (called `cao_method`) finds these centroids as expected:

```python
>>> cao_method(X, 3)
array([['H', 'M', 2, 2, 4],
       ['V', 'H', 4, 5, 4],
       ['M', 'L', 2, 4, 4]], dtype=object)
```
### Performance

As an addition to this, I believe that my implementation has led to a performance improvement since I do not rebuild the density-dissimilarity matrix (this is currently denoted as `dd`) for each cluster. Instead, I construct a new row when the next centroid is selected.

```python
>>> %timeit init_cao(X, 3)
901 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit cao_method(X, 3)
183 µs ± 5.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

This performance improvement is seen particularly as k increases. For instance, with the [zoo animal dataset](https://www.kaggle.com/uciml/zoo-animal-classification/), the performance improvement is rather substantial:

```python
>>> df = pd.read_csv('../data/zoo,csv')
>>> X = df[[col for col in df.columns if col not in ['animal_name', 'class_type']]].values
>>> %timeit init_cao(X, 7)
2.23 s ± 59.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>>> %timeit cao_method(X, 7)
9.26 ms ± 141 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

I appreciate the time you've taken to read this issue, and hope that you are open to my suggestions. Of course, I am open to discussion about this topic and am eager to hear from you soon.

**Comment by daffidwilde** [comment]
Apologies but I realise I have made a mistake. The implementation is correct as it stands, but I would still be happy to put in the performance improvement if you want it.

Cheers!

**Comment by nicodv** [comment]
@daffidwilde Performance improvements are always welcome. :)

Go ahead and make a PR, if you will.
