### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by aclarkData** [nicodv/kmodes#68]
Hello, 

When I try and run the tool, I get a type error. No matter what data I put in, I have the same error, with our without the categorical argument. 

Thanks,

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-a0d1a312ac1e> in <module>()
      5 kproto = KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)
----> 6 clusters = kproto.fit_predict(X, categorical=[1,2,3,4,5,6,7,8])

~/anaconda3/lib/python3.6/site-packages/kmodes/kmodes.py in fit_predict(self, X, y, **kwargs)
    374         predict(X).
    375         """
--> 376         return self.fit(X, **kwargs).predict(X, **kwargs)
    377 
    378     def predict(self, X, **kwargs):

~/anaconda3/lib/python3.6/site-packages/kmodes/kmodes.py in fit(self, X, y, **kwargs)
    365                                                self.init,
    366                                                self.n_init,
--> 367                                                self.verbose)
    368         return self
    369 

~/anaconda3/lib/python3.6/site-packages/kmodes/kmodes.py in k_modes(X, n_clusters, max_iter, dissim, init, n_init, verbose)
    175     # Convert the categorical values in X to integers for speed.
    176     # Based on the unique values in X, we can make a mapping to achieve this.
--> 177     X, enc_map = encode_features(X)
    178 
    179     n_points, n_attrs = X.shape

~/anaconda3/lib/python3.6/site-packages/kmodes/util/__init__.py in encode_features(X, enc_map)
     45     for ii in range(X.shape[1]):
     46         if fit:
---> 47             col_enc = {val: jj for jj, val in enumerate(np.unique(X[:, ii]))
     48                        if not (isinstance(val, float) and np.isnan(val))}
     49             enc_map.append(col_enc)

~/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts, axis)
    208     ar = np.asanyarray(ar)
    209     if axis is None:
--> 210         return _unique1d(ar, return_index, return_inverse, return_counts)
    211     if not (-ar.ndim <= axis < ar.ndim):
    212         raise ValueError('Invalid axis kwarg specified for unique')

~/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py in _unique1d(ar, return_index, return_inverse, return_counts)
    275         aux = ar[perm]
    276     else:
--> 277         ar.sort()
    278         aux = ar
    279     flag = np.concatenate(([True], aux[1:] != aux[:-1]))

TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by aclarkData** [comment]
Okay! Thank you!

**Comment by BanuSelinTosun** [comment]
I am having the same problem, I converted all my features to "str" and still getting the same issue. Even more weird thing is, when I use a subset of the same data, it works well; if I feed in the entire data it gives this "TypeError: '>' not supported between instances of 'float' and 'str'" error. Any insight on that?

**Comment by nicodv** [comment]
@BanuSelinTosun , that is consistent with the issue described above: you might have multiple types in one or more of your data columns.

Did you try applying `numpy`'s `.astype` on your columns?

**Comment by gauhar-tier** [comment]
Hi! Im having the same problem.  No nans, everything is numeric float, it still returns that error. What should I do?

**Comment by nicodv** [comment]
@gauhar-tier , please provide a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) and I can take another look at this problem.
