### ISSUE TITLE
 TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by Upendran-Akshay** [nicodv/kmodes#72]
Hi,

when i commit the code below:

from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = "Nan", strategy = "mean",axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

it can't run with the "  TypeError: unhashable type: 'slice'". could you please tell me how can solve this problem? Thank very much!

**Comment by nicodv** [comment]
Does this even have anything to do with `kmodes` at all? Closing this until you can prove otherwise.

**Comment by Upendran-Akshay** [comment]
Hi,

when i commit the code below:

from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = "Nan", strategy = "mean",axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

it can't run with the " TypeError: unhashable type: 'slice'". could you please tell me how can solve this problem? Thank very much!

**Comment by nicodv** [comment]
Duplicate of: https://github.com/nicodv/kmodes/issues/67
