### ISSUE TITLE
KModes module cannot be found

### ISSUE THREAD

**Issue by bendiste** [nicodv/kmodes#75]
Hello,

Even if I downloaded the whole package and installed according to the instructions, I cannot use it. I want to use K-prototypes algorithm but it cannot even import k-modes in the first place. When I import k-modes like this :
`from kmodes.KModes import KModes`

I have this error:

> ModuleNotFoundError: No module named 'kmodes.KModes'

I even placed this package's py folders into the same file which is my workspace for my codes. What could be the reason? How can I fix it?

**Comment by Vlets** [comment]
Which IDE are you using?
 
If you are working on PyCharm, try going under Preferences>Project>Project Interpreter and click on the '+' to install the kmodes from there. Note if you use Anaconda as the interpreter you might need to click on the round green circle close to the '+' to deactivate it before the package can be found in the list.

Also make sure you installed the package correctly. Usually installing with pip is a safe bet.

**Comment by nicodv** [comment]
Try `from kmodes.kmodes import KModes` instead. Note the capitalization.

**Comment by dengxingwang** [comment]
> Note the capitalization.

It still does't work.Is there any other solution?

**Comment by Godlikemandyy** [comment]
I try to use this package, but I also get this error: "ModuleNotFoundError: No module named 'kmodes.kmodes'; 'kmodes' is not a package"

**Comment by Godlikemandyy** [comment]
I try to use this package, but I also get this error: "ModuleNotFoundError: No module named 'kmodes.kmodes'; 'kmodes' is not a package"

**Comment by sinkingsun2** [comment]
I had same issue, Godlikemandyy, it turned out that I named my test file as kmodes.py, and current directory is in sys.path. so python use my test file as the library. 
I guess you may made same mistake as me. just rename your script as something else, everything is fine.

**Comment by d3wd69420** [comment]
for anyone trying to run kmodes on an online notebook like jupyter or kaggle I found that it works to put it down like this: 

from kmodes.kmodes import KModes 

for some reason capitalizing the m in kmodes causes it to run just fine
