### ISSUE TITLE
TypeError: '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by Rahib4** [nicodv/kmodes#80]
I am trying to run kmodes on a mix data set (categorical + numeric). If i use only numeric variable, the code runs fine only when i include categorical variables i get this issue.

`import numpy as np
import pandas as pd
from kmodes.kmodes import KModes

FileAddress = 'C:/xxx/xxxx/InputData_v1.csv'
df = pd.read_csv(FileAddress)
data = df.iloc[:,:8]
print(data)

km = KModes(n_clusters=5, init='Huang', n_init=20, verbose=1)

clusters = km.fit_predict(data)

print(km.cluster_centroids_)`

**Comment by d-schmitt** [comment]
Hi Rahib4,

from your provided code it looks like you are using the kmodes algorithm for mixed data clustering.

As written in the readme: 

> k-modes is used for clustering categorical variables. (...) The k-prototypes algorithm combines k-modes and k-means and is able to cluster mixed numerical / categorical data.

Therefore kmodes is not suitable for a mixture of categorical and numerical variables, but instead kprototypes should work with your data.
Have you tried using kprototypes, e.g. using the following code? 

`from kmodes.kprototypes import KPrototypes

FileAddress = 'C:/xxx/xxxx/InputData_v1.csv'
df = pd.read_csv(FileAddress)
data = df.iloc[:,:8]

kp = KPrototypes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = kp.fit_predict(data)

print(kp.cluster_centroids_)`

**Comment by LuLing06** [comment]
how to add the categorical data? when I did: categorical=columns name, I got a error: '<' not supported between instances of 'int' and 'range''

Thanks!

**Comment by d-schmitt** [comment]
Hi @LuLing06,

categorial columns are handed over not by their column names, but by the column indexes in form of a list.
Imagine you have a dataframe or array with three columns in this order: Country, Median Income and Inhabitants. If you would want to supply the country as a categorial variable you would have to assign the categorical parameter with `categorical=[0]`.
Another example for that can be found in the stocks example: https://github.com/nicodv/kmodes/blob/master/examples/stocks.py

Hope that helps!

**Comment by srikrishna75** [comment]
Facing error while running kprototypes 
![Screenshot (8)](https://user-images.githubusercontent.com/49230211/65890612-c7fd4100-e3c0-11e9-9428-57777ae505c8.png)

**Comment by nicodv** [comment]
@srikrishna75 , see the FAQ: https://github.com/nicodv/kmodes#faq
