### ISSUE TITLE
Can I set a minimum number of children in the cluster?

### ISSUE THREAD

**Issue by vlall** [nicodv/kmodes#81]
I have an odd set of categories i'm clustering. I get:

Cluster 0: 10,000 children
Cluster 1: 1 child
Cluster 2: 1 child
Cluster 3: 1 child

Now i've been working around this by making a While loop that clusters, checks the members in each cluster, and if it's too small, clusters again without the outliers. However, I want to do something more efficient. Another method is increasing the cluster sizes every iteration. Any suggestions that do not require looping ?

**Comment by zextserg** [comment]
@nicodv thank you for such great lib it's amazing!
May be you can explain more detailed, how can make minimum size of cluster childrens?
Do you talk about line: `if not membship[old_clust, :].any():` ?
I tried to look at `len(membship[old_clust, :])` but it always contain > 1 elements and final clusters still have only one children.

**Comment by nicodv** [comment]
Yes, that's the line I was talking about, @zextserg . What you describe shouldn't be possible, so I suggest some careful debugging.
