### ISSUE TITLE
Not getting more than 256 clusters

### ISSUE THREAD

**Issue by nilkeshpatra** [nicodv/kmodes#85]
Hello,
I have a data frame with more than 11k records and I know that at least 700 unique rows are there. But still I am getting only 256 clusters in spite of passing the argument n_clusters=500.
What can be the issue?
I was checking the kmodes code, I am only suspecting the issue in the function get_unique_rows. There is only one place where n_clusters get reassigned in the code.

Regards,
Nilkesh

**Comment by nicodv** [comment]
`get_unique_rows` should only reduce `n_clusters` to 700, if there's really that many unique rows. You can pull the code and add a print statement there to be sure.

Note that 100s of clusters might be too many. You're saying you want the algorithm to come up with at least 500 clusters, potential with lots of them consisting of single points. Those are very hard to find for the algorithm, though. Try running in verbose mode to see the convergence behavior. I suspect there are many empty clusters.

**Comment by nilkeshpatra** [comment]
I just created a test file with 3 columns and 400 unique rows. After applying kmodes with n_clusters=300, again I got 256 clusters only. There is no empty cluster also.
Hence the issue is there, but need to know the solution.

**Comment by nicodv** [comment]
Ah, it's because I'm using numpy's `uint8`, which only goes up to 256.

Replacing it by a `uint16` should do the trick.

**Comment by nicodv** [comment]
This is an easy fix, but I won't have time for a while. You might as well make the change yourself and submit a pull request, if you will.

**Comment by nilkeshpatra** [comment]
I made the changes locally and it is working fine. Just a thought here, if we make the change to uint16, still we limit the number of clusters to 65536. Should we change it to uint64, so that the limit will be large enough?

**Comment by nicodv** [comment]
@nilkeshpatra , good to know. Hundreds of clusters is already a ridiculously large number for a clustering application, no need to aim for many thousands.

**Comment by nicodv** [comment]
Fixed with: https://github.com/nicodv/kmodes/pull/89

**Comment by nicodv** [comment]
It will be in the version after 0.9
