### ISSUE TITLE
Cao Initialisation for k-Prototype

### ISSUE THREAD

**Issue by mkauka** [nicodv/kmodes#86]
Hi, 

I've got a question regarding the Cao initialisation procedure. 
I understand that for categorical data, the centroids are computed deterministically. In k-modes, the number of initialisations is hence set to 1.
But when using k-prototype, the numerical aspects of the centroids are drawn from a normal distribution. Nonetheless, the number of initialisations is set to 1. Is there a way to do multiple initialisations for this case?

Thanks!

Best regards
Milena

**Comment by nicodv** [comment]
Valid point. It would make sense to remove the hardcoded `n_init=1` for k-prototypes, indeed.

**Comment by nicodv** [comment]
Fixed by https://github.com/nicodv/kmodes/pull/90
