### ISSUE TITLE
weight parameter for categorical attributes for cluster

### ISSUE THREAD

**Issue by hajarhomayouni** [nicodv/kmodes#88]
In [HUANG97] paper, there is a weight parameter for categorical attributes for cluster. How did you set this parameter? 
Is there a way to manually set this parameter?

**Comment by nicodv** [comment]
I believe you are referring to the gamma parameter in the k-prototypes algorithm, which determines the trade-off between the categorical and numerical part of the algorithm.

It can be set with `gamma`, as explained here: https://github.com/nicodv/kmodes/blob/master/kmodes/kprototypes.py#L369
