### ISSUE TITLE
Mixed datatypes

### ISSUE THREAD

**Issue by hugo-pires** [nicodv/kmodes#9]
Is there any way to separate categorical from quantitative features?

thank you

**Comment by nicodv** [comment]
What do you mean by "separate"?

**Comment by hugo-pires** [comment]
Thank you. I mean if there is any way to label each feature as categorical or quantitative?

**Comment by nicodv** [comment]
The stocks example shows how to do this: `kproto.fit_predict(X, categorical=[1, 2])`, where 1 and 2 are the column indices of the categorical variables. The rest are treated as numerical.

**Comment by hugo-pires** [comment]
Thanks
