### ISSUE TITLE
n_jobs missing

### ISSUE THREAD

**Issue by miljansto** [nicodv/kmodes#94]
Hello there, 

Firstly I would like to thank you for the great work. 

Now I have a small issue on using it. My version of kmodes must be up to date (0.9). 
My terminal displays this when I use the command "pip install --upgrade kmodes"
"Requirement already up-to-date: kmodes in /Users/miljanstojiljkovic/anaconda3/lib/python3.6/site-packages (0.9)"
The problem is that in my notebook it doesn't take into account the argument n_jobs. 
Here's a display of all the arguments it has : 
"Init signature: KModes(n_clusters=8, max_iter=100, cat_dissim=<function matching_dissim at 0x1a1abafc80>, init='Cao', n_init=1, verbose=0)"
Furthermore, my kernel dies everytime it finishes running the fit function. 
Do you have any info on that ? 

Thank you in advance for reading my issue,
Miljan.

**Comment by nicodv** [comment]
`n_jobs` has been introduced after the 0.9 release. :) You'll have to wait until the next release, or build the package yourself.

As for the kernel dying, I would need a minimal reproducible example to debug further. Nobody has reported this problem before.

**Comment by miljansto** [comment]
Thanks for the quick answer. 
For the kernel dying, I resolved it by keeping the default parameters.

**Comment by klepikhina** [comment]
I notice that when trying to run:
`km = KPrototypes(n_clusters=20, init='Huang', n_init=1, n_jobs=-1, verbose=1)`
that I get an error that says:
`__init__() got an unexpected keyword argument 'n_jobs'`

I noticed that this should be fixed in the next release - when will that be?

**Comment by nicodv** [comment]
@klepikhina , I'm not sure but in the meantime you can build the latest version from source, as described here: https://github.com/nicodv/kmodes#installation

**Comment by klepikhina** [comment]
Hi @nicodv, thank you so much for the super quick response! I'm still having problems after building it by hand. I build using the instructions described in https://github.com/nicodv/kmodes#installation, then in my script, `from kmodes.kprototypes import KPrototypes` and get the same error `__init__() got an unexpected keyword argument 'n_jobs'`
