### ISSUE TITLE
Match between centroids and labels

### ISSUE THREAD

**Issue by melsener** [nicodv/kmodes#95]
Hi!
Thank you for this module!
My question is, is there a matching between labels and centroids? I mean for example label 3's centroid is `km.cluster_centroids_[3]` ?

**Comment by d-schmitt** [comment]
Hi @melsener,

the cluster label of all elements in the cluster can be accessed via the `.labels_` option :
```
kproto = KPrototypes(n_clusters = 5, init = 'Huang', n_init = 1, verbose = 2)
clusters = kproto.fit(df, categorical = [1,2])
clusterlabels = clusters.labels_
```
So as far as I know you would have to indirectly match those labels with the cluster centroids.

**Comment by melsener** [comment]
@d-schmitt  I didn't asked about accessing labels, my question is the mapping between the centroid index and the label. For example, I am looking for which centroid owns the last instance? 
```
labels = clusters.labels_
last_instance_centroid = clusters.cluster_centroids_[labels[-1]]
```

**Comment by nicodv** [comment]
@melsener , I believe you answered your own question, right? That code seems to do what you want.
